# Generated by Django 2.0.3 on 2018-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_your_mom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cymuser',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
