# Generated by Django 2.0.4 on 2018-04-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_your_mom', '0002_cymuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='cymuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
